// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mat_partner_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MatPartnerData _$MatPartnerDataFromJson(Map<String, dynamic> json) =>
    MatPartnerData(
      mestoNaziv: json['mesto_naziv'] as String?,
      selectNaziv: json['select_naziv'] as String?,
      tpp: json['tpp'] as String?,
      selectNazivKlient: json['select_naziv_klient'] as String?,
      tipPartner: (json['tip_partner'] as num?)?.toInt(),
      id: (json['id'] as num?)?.toInt(),
      naziv: json['naziv'] as String?,
      adresa: json['adresa'] as String?,
      tel: json['tel'] as String?,
      fax: json['fax'] as String?,
      danocen: json['danocen'] as String?,
      emb: json['emb'] as String?,
      mesto: (json['mesto'] as num?)?.toInt(),
      ime: json['ime'] as String?,
      prezime: json['prezime'] as String?,
      tatko: json['tatko'] as String?,
      logo: json['logo'] as String?,
      re: (json['re'] as num?)?.toInt(),
      logotext: json['logotext'] as String?,
      status: (json['status'] as num?)?.toInt(),
      limit: (json['limit'] as num?)?.toDouble(),
      cenovnik: (json['cenovnik'] as num?)?.toInt(),
      email: json['email'] as String?,
      mail: json['mail'] as String?,
      url: json['url'] as String?,
      cena: (json['cena'] as num?)?.toDouble(),
      aktiven: (json['aktiven'] as num?)?.toInt(),
      nazivSkraten: json['naziv_skraten'] as String?,
      adresaLatitude: (json['adresa_latitude'] as num?)?.toDouble(),
      adresaLongitude: (json['adresa_longitude'] as num?)?.toDouble(),
      pravnoLice: (json['pravno_lice'] as num?)?.toInt(),
      tsIns: json['ts_ins'] == null
          ? null
          : DateTime.parse(json['ts_ins'] as String),
      tsUpd: json['ts_upd'] == null
          ? null
          : DateTime.parse(json['ts_upd'] as String),
      usrIns: json['usr_ins'] as String?,
      usrUpd: json['usr_upd'] as String?,
      custom1: json['custom1'] as String?,
      custom2: json['custom2'] as String?,
      custom3: json['custom3'] as String?,
      valDenovi: (json['val_denovi'] as num?)?.toInt(),
      memorandum: json['memorandum'] as String?,
      memorandumText: json['memorandum_text'] as String?,
      logoEn: json['logo_en'] as String?,
      logotextEn: json['logotext_en'] as String?,
    );

Map<String, dynamic> _$MatPartnerDataToJson(MatPartnerData instance) =>
    <String, dynamic>{
      'mesto_naziv': instance.mestoNaziv,
      'select_naziv': instance.selectNaziv,
      'tpp': instance.tpp,
      'select_naziv_klient': instance.selectNazivKlient,
      'tip_partner': instance.tipPartner,
      'id': instance.id,
      'naziv': instance.naziv,
      'adresa': instance.adresa,
      'tel': instance.tel,
      'fax': instance.fax,
      'danocen': instance.danocen,
      'emb': instance.emb,
      'mesto': instance.mesto,
      'ime': instance.ime,
      'prezime': instance.prezime,
      'tatko': instance.tatko,
      'logo': instance.logo,
      're': instance.re,
      'logotext': instance.logotext,
      'status': instance.status,
      'limit': instance.limit,
      'cenovnik': instance.cenovnik,
      'email': instance.email,
      'mail': instance.mail,
      'url': instance.url,
      'cena': instance.cena,
      'aktiven': instance.aktiven,
      'naziv_skraten': instance.nazivSkraten,
      'adresa_latitude': instance.adresaLatitude,
      'adresa_longitude': instance.adresaLongitude,
      'pravno_lice': instance.pravnoLice,
      'ts_ins': instance.tsIns?.toIso8601String(),
      'ts_upd': instance.tsUpd?.toIso8601String(),
      'usr_ins': instance.usrIns,
      'usr_upd': instance.usrUpd,
      'custom1': instance.custom1,
      'custom2': instance.custom2,
      'custom3': instance.custom3,
      'val_denovi': instance.valDenovi,
      'memorandum': instance.memorandum,
      'memorandum_text': instance.memorandumText,
      'logo_en': instance.logoEn,
      'logotext_en': instance.logotextEn,
    };
